### ISSUE TITLE
macaca run   报错

### ISSUE THREAD

**Issue by javaliquan** [macacajs/macaca-cli#14]
> > /usr/local/Cellar/node/5.1.0/libexec/npm/lib/node_modules/macaca-client/node_modules/mocha/lib/utils.js:577
> >       if (!files.length) throw new Error("cannot resolve path (or pattern) '" + path + "'");
> >                          ^

Error: cannot resolve path (or pattern) 'macaca-test'
    at Object.lookupFiles (/usr/local/Cellar/node/5.1.0/libexec/npm/lib/node_modules/macaca-client/node_modules/mocha/lib/utils.js:577:32)
    at /usr/local/Cellar/node/5.1.0/libexec/npm/lib/node_modules/macaca-client/node_modules/mocha/bin/_mocha:320:30
    at Array.forEach (native)
    at Object.<anonymous> (/usr/local/Cellar/node/5.1.0/libexec/npm/lib/node_modules/macaca-client/node_modules/mocha/bin/_mocha:319:6)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3

> > Test completed!

然后使用的文档进不去

**Comment by xudafeng** [comment]
文档相关: macacajs/macaca#8

**Comment by xudafeng** [comment]
@javaliquan 执行的目录是测试用例的 repo ，不要搞混了

**Comment by xudafeng** [comment]
请查看[文档](http://macacajs.github.io/macaca/guide.html#/environment-setup)
