### ISSUE TITLE
环境搭建完之后跑测试用例

### ISSUE THREAD

**Issue by loneyao** [macacajs/macaca-cli#41]
clydeiMac:macaca-test-sample cly$ macaca run --verbose

> > index.js:30:12 [master] pid:1303 webdriver server start with config:
> >  { port: 3456,
> >   window: true,
> >   ip: '192.168.3.70',
> >   host: 'clydeiMac.local',
> >   loaded_time: '2016-06-12 10:46:52' }
> > middlewares.js:30:10 [master] pid:1303 base middlewares attached
> > router.js:118:10 [master] pid:1303 router set
> > webdriver sdk launched
> > 
> >   macaca mobile sample
> > 
> > responseHandler.js:24:12 [master] pid:1303 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","app":"/Users/cly/macaca-test-sample/app/ios-app-bootstrap.zip"}}
> > session.js:60:10 [master] pid:1303 Creating session, sessionId: 4bb184ce-b250-4b35-9ee5-9249b19275de.
> > helper.js:205:12 [master] pid:1303 Unzipping local app form /Users/cly/macaca-test-sample/app/ios-app-bootstrap.zip
> > CFBundleIdentifier is xudafeng.ios-app-bootstrap
> > Get bundleId xudafeng.ios-app-bootstrap from plist /var/folders/d_/fd6lqsmx7jx_bcj2zvsq8hhw0000gn/T/ios-app-bootstrap.app/Info.plist
> > macaca-ios.js:182:10 [master] pid:1303 Get available devices [{"name":"iPhone 4s","udid":"6D681EA6-5A58-41A2-B2A5-CFAEFE8315C4","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 5","udid":"0271473C-8241-45F8-AA89-68AB2A962B63","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 5s","udid":"4D63A6A7-455E-4524-A2AD-8945440A4763","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 6","udid":"E0B98126-B342-4EB3-BEAB-B76070248688","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 6 Plus","udid":"1A292B44-0593-4685-AB98-8CB58564A033","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 6s","udid":"9748E735-DBC1-4F79-AD77-5FEC0B47EF0D","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPhone 6s Plus","udid":"4E060382-8591-42F3-9482-9A950189BCF8","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad 2","udid":"30E7C063-8218-445D-9586-E12764218676","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad Retina","udid":"78E3792F-8E51-426F-8098-84FF8C664798","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad Air","udid":"7B19A7CB-A7F1-49D9-9BE8-0C0A2183BCD2","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad Air 2","udid":"AE713A51-57DD-4DF7-AF7C-5C407BBFA654","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"iPad Pro","udid":"6DD9013C-7162-4E99-8E56-A216750DB1F8","state":"Shutdown","available":true,"runtime":"iOS 9.3"},{"name":"Apple TV 1080p","udid":"DAB3248A-624A-4710-80CA-369D97AB5CA6","state":"Shutdown","available":true,"runtime":"tvOS 9.2"},{"name":"Apple Watch - 38mm","udid":"D8C3455A-8316-40D8-8D3C-D05F6E39489D","state":"Shutdown","available":true,"runtime":"watchOS 2.2"},{"name":"Apple Watch - 42mm","udid":"220F18DA-1BA4-470C-9F5E-6BD5584D67D3","state":"Shutdown","available":true,"runtime":"watchOS 2.2"}]
> > macaca-ios.js:215:12 [master] pid:1303 Kill simulator failed Error: Command failed: killAll Simulator
> > No matching processes belonging to you were found
> > 
> > macaca-ios.js:221:12 [master] pid:1303 Shutdown simulator 4D63A6A7-455E-4524-A2AD-8945440A4763 failed Error: Command failed: xcrun simctl shutdown "4D63A6A7-455E-4524-A2AD-8945440A4763"
> > An error was encountered processing the command (domain=com.apple.CoreSimulator.SimError, code=159):
> > Unable to shutdown device in current state: Shutdown
> > 
> > agent path: /usr/local/lib/node_modules/macaca-ios/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcworkspace
> > macaca-ios.js:132:10 [master] pid:1303 {
> >     "bundleId": "xudafeng.ios-app-bootstrap",
> >     "platformName": "iOS",
> >     "platformVersion": "9.3",
> >     "app": "/var/folders/d_/fd6lqsmx7jx_bcj2zvsq8hhw0000gn/T/ios-app-bootstrap.app/"
> > }
> > xctest-client.js:246:12 [master] pid:1303 xcode version: 7.3.1
> > xctest-client.js:150:16 [master] pid:1303 tail: /Users/cly/Library/Logs/CoreSimulator/4D63A6A7-455E-4524-A2AD-8945440A4763/system.log: No such file or directory
> > 
> > xctest-client.js:158:16 [master] pid:1303 bootstrap exit with code: 1, signal: null
> > responseHandler.js:63:12 [master] pid:1303 Send Error Respone to Client: undefined

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (/usr/local/lib/node_modules/macaca-cli/node_modules/koa/lib/context.js:91:23)
      at Object.module.exports (/usr/local/lib/node_modules/macaca-cli/node_modules/webdriver-server/lib/server/responseHandler.js:66:17)
      at throw (native)
      at onRejected (/usr/local/lib/node_modules/macaca-cli/node_modules/co/index.js:81:24)
      at process._tickCallback (internal/process/next_tick.js:103:7)

> > ```
> > 1) "before all" hook
> > ```
> > 
> > responseHandler.js:24:12 [master] pid:1303 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session, jsonBody: {}
> > responseHandler.js:32:14 [master] pid:1303 Send HTTP Respone to Client: 405 Method Not Allowed
> > 
> > ```
> > 2) "after all" hook
> > ```
> > 
> >   0 passing (8s)
> > 
> >   2 failing
> > 
> >   1) macaca mobile sample "before all" hook:
> >      [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","app":"/Users/cly/macaca-test-sample/app/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
> >   Error: [init({"autoAcceptAlerts":true,"platformName":"iOS","platformVersion":"9.3","deviceName":"iPhone 5s","app":"app/ios-app-bootstrap.zip"})] The environment you requested was unavailable.
> >       at node_modules/macaca-wd/wd/lib/webdriver.js:134:15
> >       at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
> >       at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
> >       at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
> >       at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
> >       at endReadableNT (_stream_readable.js:926:12)
> >       at _combinedTickCallback (internal/process/next_tick.js:74:11)
> >       at process._tickCallback (internal/process/next_tick.js:98:9)
> > 
> >   2) macaca mobile sample "after all" hook:
> >      Error: [quit()] Unexpected data in simpleCallback.
> >       at exports.newError (node_modules/macaca-wd/wd/lib/utils.js:139:13)
> >       at .<anonymous> (node_modules/macaca-wd/wd/lib/callbacks.js:42:12)
> >       at cb (node_modules/macaca-wd/wd/lib/webdriver.js:165:22)
> >       at node_modules/macaca-wd/wd/lib/webdriver.js:179:5
> >       at Request._callback (node_modules/macaca-wd/wd/lib/http-utils.js:87:7)
> >       at Request.self.callback (node_modules/macaca-wd/node_modules/request/request.js:368:22)
> >       at Request.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1219:14)
> >       at IncomingMessage.<anonymous> (node_modules/macaca-wd/node_modules/request/request.js:1167:12)
> >       at endReadableNT (_stream_readable.js:926:12)
> >       at _combinedTickCallback (internal/process/next_tick.js:74:11)
> >       at process._tickCallback (internal/process/next_tick.js:98:9)
> > 
> > Test completed!

**Comment by loneyao** [comment]
解决了
