### ISSUE TITLE
跑脚本报错时The environment you requested was unavailable.

### ISSUE THREAD

**Issue by panghp** [macacajs/macaca-cli#50]
环境信息：
node version: v4.5.0
npm:2.15.9
os:win7 x64
macaca:1.1.2

问题：
macaca安装成功后(运行test-sample里的macaca-desktop-sample.test.js是正常的)，运行脚本报错，报错信息如下：

  InternalServerError: Internal Server Error
      at Object.module.exports.throw (C:\Users\XXX\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\node_modules\koa\lib\context.js:91:23)
      at Object.module.exports (C:\Users\XXX\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\webdriver-server\lib\server\responseHandler.js:53:17)
      at throw (native)
      at onRejected (C:\Users\XXX\AppData\Roaming\npm\node_modules\macaca-cli\node_modules\co\index.js:81:24)
      at process._tickCallback (node.js:369:9)

> > ```
> > 1) "before all" hook
> > ```
> > 
> >   0 passing (2s)
> >   1 failing

  1) macaca mobile sample "before all" hook:
     Error: [init({"autoAcceptAlerts":true,"platformName":"Android","package":"com.XX.android","activity":"com.XX.android.XXActivity"})] The environment you requested was unavailable.
      at C:\Users\XXX\node_modules\webdriver-client\node_modules\macaca-wd\wd\lib\webdriver.js:134:15
      at Request._callback (C:\Users\XXX\node_modules\webdriver-client\node_modules\macaca-wd\wd\lib\http-utils.js:87:7)
      at Request.self.callback (C:\Users\XXX\node_modules\webdriver-client\node_modules\macaca-wd\node_modules\request\request.js:368:22)
      at Request.<anonymous> (C:\Users\XXX\node_modules\webdriver-client\node_modules\macaca-wd\node_modules\request\request.js:1219:14)
      at IncomingMessage.<anonymous> (C:\Users\XXX\node_modules
![macaca](https://cloud.githubusercontent.com/assets/8555961/18124799/5d7561f0-6fa6-11e6-80fe-bf0b0b945940.png)
\webdriver-client\node_modules\macaca-wd\node_modules\request\request.js:1167:12)
      at endReadableNT (_stream_readable.js:921:12)

**Comment by xudafeng** [comment]
https://testerhome.com/wiki/macaca

**Comment by panghp** [comment]
已解决，是因为安装adb时安装在D:\Program Files (x86)\Android\android-sdk下了，这路径中有空格，macaca不支持这样的路径，把adb安装在根目录下即可
