### ISSUE TITLE
xctest client proxy error with: Error: connect ECONNREFUSED 172.18.156.69:8100

### ISSUE THREAD

**Issue by 183181731** [macacajs/macaca-cli#51]
os: os x 10.11.6
macaca version:1.1.2
ios driver: 1.0.36
device: iPhone6S(9.3.5)
真机运行时，大概率会反复出现此错误(同样的代码步骤可以正常运行过)。出现此提示失败后，设备上过了一段时间才会自动启动起WebDriverAgent并自动关闭。

ERROR LOG:

```
QA-deMac-mini:~ qa$ macaca server --verbose
>> index.js:17:12 [master] pid:6048 webdriver server start with config:
 { port: 3456,
  verbose: true,
  ip: '192.168.241.195',
  host: 'QA-deMac-mini.local',
  loaded_time: '2016-09-12 18:15:55' }
>> middlewares.js:17:10 [master] pid:6048 base middlewares attached
>> router.js:108:10 [master] pid:6048 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:6048 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformVerison":"9.3.5","platformName":"iOS","bundleId":"com.nd.app.factory.jianggongyouth","udid":"<udid>","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:6048 Creating session, sessionId: e9d76ab1-ae08-4d74-890b-0f4f5f1dddda.
>> xctest-client.js:43:14 [master] pid:6048 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:130:10 [master] pid:6048 {
    "bundleId": "com.nd.app.factory.jianggongyouth",
    "platformName": "iOS",
    "browserName": "firefox"
}
>> xctest-client.js:183:12 [master] pid:6048 xcode version: 7.3.1
>> WebDriverAgent version: 1.0.25
>> xctest-client.js:156:14 [master] pid:6048 2016-09-12 18:16:03.293 xcodebuild[6054:27353] [MT] IDETestOperationsObserverDebug: (87020BAC-33C0-4DE0-BB81-50C355B6773B) Beginning test session 87020BAC-33C0-4DE0-BB81-50C355B6773B with Xcode 7D1014 on target <DVTiOSDevice: 0x7f85c5683720> {
        deviceSerialNumber:         FK1QF2JTGRYC
        identifier:                 <udid>
        deviceClass:                iPhone
        deviceName:                 My iPhone
        deviceIdentifier:           <udid>
        productVersion:             9.3.5
        buildVersion:               13G36
        deviceSoftwareVersion:      9.3.5 (13G36)
        deviceArchitecture:         arm64
        deviceTotalCapacity:        59669319680
        deviceAvailableCapacity:    7193366528
        deviceIsTransient:          NO
        ignored:                    NO
        deviceIsBusy:               NO
        deviceIsActivated:          YES
        deviceActivationState:      Activated
        deviceType:                 <DVTDeviceType:0x7f85c53c0a90 Xcode.DeviceType.iPhone>
        supportedDeviceFamilies:    (
    1
)
        applications:              (null)
        provisioningProfiles:      (null)
        activityProgress:          -2
        activityTitle:             
        hasInternalSupport:        NO
        isSupportedOS:             YES
        developerDiskMountError:   (null)
(null)
    } (9.3.5 (13G36))

>> xctest-client.js:156:14 [master] pid:6048 2016-09-12 18:16:03.296 xcodebuild[6054:27355]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-drmzhetqodgefhaqpyureuezairh/Logs/Test/616A811A-9156-45F8-A4E1-969BE3F2DAD9/Session-2016-09-12_18:16:03-bizmtg.log

>> xctest-client.js:156:14 [master] pid:6048 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/7566f7ff6f0cd873d892945ee2a11b48/<udid>/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-drmzhetqodgefhaqpyureuezairh/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.BC8Qop/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
    dst_ipa: /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.BC8Qop/WebDriverAgentRunner-Runner.app_sparse.ipa

>> xctest-client.js:156:14 [master] pid:6048 __MDMDirectoryDiff_block_invoke37:1473 calling writeDictToFile with: /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.BC8Qop/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> xctest-client.js:156:14 [master] pid:6048 writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.BC8Qop/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> proxy.js:54:14 [master] pid:6048 Proxy: /session:POST to http://172.18.156.69:8100/session:POST with body: {"desiredCapabilities":{"bundleId":"com.nd.app.factory.jianggongyouth","platformName":"iOS","browserName":"firefox"}}
>> proxy.js:58:18 [master] pid:6048 xctest client proxy error with: Error: connect ECONNREFUSED 172.18.156.69:8100
/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169
  throw new Error(res);
  ^

Error: >> proxy.js:58:18 [master] pid:6048 xctest client proxy error with: Error: connect ECONNREFUSED 172.18.156.69:8100
    at Logger.error (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request._callback (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

**Comment by 183181731** [comment]
下面是相同的环境步骤和脚本，正常运行的时候的LOG：

```
QA-deMac-mini:~ qa$ macaca server --verbose
>> index.js:17:12 [master] pid:6233 webdriver server start with config:
 { port: 3456,
  verbose: true,
  ip: '192.168.241.195',
  host: 'QA-deMac-mini.local',
  loaded_time: '2016-09-12 18:27:38' }
>> middlewares.js:17:10 [master] pid:6233 base middlewares attached
>> router.js:108:10 [master] pid:6233 router set
>> webdriver sdk launched
>> responseHandler.js:11:12 [master] pid:6233 Recieve HTTP Request from Client: method: POST url: /wd/hub/session, jsonBody: {"desiredCapabilities":{"platformVerison":"9.3.5","platformName":"iOS","bundleId":"com.nd.app.factory.jianggongyouth","udid":"<udid>","browserName":"firefox","version":"","javascriptEnabled":true,"platform":"ANY"}}
>> session.js:47:10 [master] pid:6233 Creating session, sessionId: 441a9989-60ff-4739-b4d2-50f27820434d.
>> xctest-client.js:43:14 [master] pid:6233 project path: /usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/webdriveragent/WebDriverAgent/WebDriverAgent.xcodeproj
>> macaca-ios.js:130:10 [master] pid:6233 {
    "bundleId": "com.nd.app.factory.jianggongyouth",
    "platformName": "iOS",
    "browserName": "firefox"
}
>> xctest-client.js:183:12 [master] pid:6233 xcode version: 7.3.1
>> WebDriverAgent version: 1.0.25
>> xctest-client.js:156:14 [master] pid:6233 2016-09-12 18:27:46.383 xcodebuild[6239:31125]  IDETestOperationsObserverDebug: Writing diagnostic log for test session to:
/Users/qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-drmzhetqodgefhaqpyureuezairh/Logs/Test/A5869874-0166-4844-96D2-AE2D4D054A6C/Session-2016-09-12_18:27:46-ZHaBd2.log

>> xctest-client.js:156:14 [master] pid:6233 2016-09-12 18:27:46.385 xcodebuild[6239:31122] [MT] IDETestOperationsObserverDebug: (F039F672-B34C-4CE0-B044-60B5CCA38212) Beginning test session F039F672-B34C-4CE0-B044-60B5CCA38212 with Xcode 7D1014 on target <DVTiOSDevice: 0x7ff0d55d59e0> {
        deviceSerialNumber:         FK1QF2JTGRYC
        identifier:                 <udid>
        deviceClass:                iPhone
        deviceName:                 My iPhone
        deviceIdentifier:          <udid>
        productVersion:             9.3.5
        buildVersion:               13G36
        deviceSoftwareVersion:      9.3.5 (13G36)
        deviceArchitecture:         arm64
        deviceTotalCapacity:        59669319680
        deviceAvailableCapacity:    7200444416
        deviceIsTransient:          NO
        ignored:                    NO
        deviceIsBusy:               NO
        deviceIsActivated:          YES
        deviceActivationState:      Activated
        deviceType:                 <DVTDeviceType:0x7ff0d53a5730 Xcode.DeviceType.iPhone>
        supportedDeviceFamilies:    (
    1
)
        applications:              (null)
        provisioningProfiles:      (null)
        activityProgress:          -2
        activityTitle:             
        hasInternalSupport:        NO
        isSupportedOS:             YES
        developerDiskMountError:   (null)
(null)
    } (9.3.5 (13G36))

>> xctest-client.js:156:14 [master] pid:6233 MDMCreateDeltaDirectory:1920 calling MDMDirectoryDiff with:
state->old_bundle: /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/7566f7ff6f0cd873d892945ee2a11b48/<udid>/WebDriverAgentRunner-Runner.app
state->new_bundle: /Users/qa/Library/Developer/Xcode/DerivedData/WebDriverAgent-drmzhetqodgefhaqpyureuezairh/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app
state->dst_bundle: /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.qOxe8B/WebDriverAgentRunner-Runner.app_sparse.ipa/Payload//WebDriverAgentRunner-Runner.app, binaryDiff flag: FALSE
    dst_ipa: /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.qOxe8B/WebDriverAgentRunner-Runner.app_sparse.ipa

>> xctest-client.js:156:14 [master] pid:6233 __MDMDirectoryDiff_block_invoke37:1473 calling writeDictToFile with: /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.qOxe8B/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist
writeDictToFile:1278 ==== Successfully wrote Manifest cache to /var/folders/7x/rvnhm1zs44j1mkq4fg6qzqqm0000gn/C/com.apple.DeveloperTools/All/Xcode/EmbeddedAppDeltas/WebDriverAgentRunner-Runner.app.qOxe8B/WebDriverAgentRunner-Runner.app_sparse.ipa/ManifestCache.plist

>> proxy.js:54:14 [master] pid:6233 Proxy: /session:POST to http://172.18.156.69:8100/session:POST with body: {"desiredCapabilities":{"bundleId":"com.nd.app.factory.jianggongyouth","platformName":"iOS","browserName":"firefox"}}
>> proxy.js:67:16 [master] pid:6233 Got response with status 200: {"value":{"sessionId":"E869379A-680D-4CD5-AE7D-45BD6A3CF533","capabilities":{"device":"iphone","browserName":"江工青年","sdkVersion":"9.3.5","CFBundleIdentifier":"com.nd.app.factory.jianggongyouth"}},"...
>> responseHandler.js:43:14 [master] pid:6233 Send HTTP Respone to Client: {"sessionId":"441a9989-60ff-4739-b4d2-50f27820434d","status":0,"value":"{\"platformVerison\":\"9.3.5\",\"platformName\":\"iOS\",\"bundleId\":\"com.nd.app.factory.jianggongyouth\",\"udid\":\"<udid>\",\"browserName\":\"firefox\",\"version\":\"\",\"javascriptEnabled\":true,\"platform\":\"ANY\"}"}
>> responseHandler.js:11:12 [master] pid:6233 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/elements, jsonBody: {"using":"xpath","value":"//XCUIElementTypeTextField[1]"}
>> proxy.js:54:14 [master] pid:6233 Proxy: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/elements:POST to http://172.18.156.69:8100/session/E869379A-680D-4CD5-AE7D-45BD6A3CF533/elements:POST with body: {"using":"xpath","value":"//XCUIElementTypeTextField[1]"}
>> proxy.js:67:16 [master] pid:6233 Got response with status 200: {"value":[{"ELEMENT":"6EF09F72-5E9F-4A80-A899-A026290F5833","type":"XCUIElementTypeTextField","label":""}],"sessionId":"441a9989-60ff-4739-b4d2-50f27820434d","status":0}
>> session.js:107:14 [master] pid:6233 Send HTTP Respone to Client: {"value":"[{\"ELEMENT\":\"6EF09F72-5E9F-4A80-A899-A026290F5833\",\"type\":\"XCUIElementTypeTextField\",\"label\":\"\"}]","sessionId":"441a9989-60ff-4739-b4d2-50f27820434d","status":0}
>> responseHandler.js:11:12 [master] pid:6233 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/element/6EF09F72-5E9F-4A80-A899-A026290F5833/clear, jsonBody: {}
>> proxy.js:54:14 [master] pid:6233 Proxy: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/element/6EF09F72-5E9F-4A80-A899-A026290F5833/clear:POST to http://172.18.156.69:8100/session/E869379A-680D-4CD5-AE7D-45BD6A3CF533/element/6EF09F72-5E9F-4A80-A899-A026290F5833/clear:POST with body: {}
>> proxy.js:67:16 [master] pid:6233 Got response with status 200: {"status":0,"id":"6EF09F72-5E9F-4A80-A899-A026290F5833","value":"","sessionId":"441a9989-60ff-4739-b4d2-50f27820434d"}
>> session.js:107:14 [master] pid:6233 Send HTTP Respone to Client: {"status":0,"id":"6EF09F72-5E9F-4A80-A899-A026290F5833","value":"","sessionId":"441a9989-60ff-4739-b4d2-50f27820434d"}
>> responseHandler.js:11:12 [master] pid:6233 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/element/6EF09F72-5E9F-4A80-A899-A026290F5833/value, jsonBody: {"value":["890707"]}
>> proxy.js:54:14 [master] pid:6233 Proxy: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/element/6EF09F72-5E9F-4A80-A899-A026290F5833/value:POST to http://172.18.156.69:8100/session/E869379A-680D-4CD5-AE7D-45BD6A3CF533/element/6EF09F72-5E9F-4A80-A899-A026290F5833/value:POST with body: {"value":["890707"]}
>> proxy.js:67:16 [master] pid:6233 Got response with status 200: {"status":0,"id":"6EF09F72-5E9F-4A80-A899-A026290F5833","value":"","sessionId":"441a9989-60ff-4739-b4d2-50f27820434d"}
>> session.js:107:14 [master] pid:6233 Send HTTP Respone to Client: {"status":0,"id":"6EF09F72-5E9F-4A80-A899-A026290F5833","value":"","sessionId":"441a9989-60ff-4739-b4d2-50f27820434d"}
>> responseHandler.js:11:12 [master] pid:6233 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/element, jsonBody: {"using":"xpath","value":"//XCUIElementTypeSecureTextField[1]"}
>> proxy.js:54:14 [master] pid:6233 Proxy: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/element:POST to http://172.18.156.69:8100/session/E869379A-680D-4CD5-AE7D-45BD6A3CF533/element:POST with body: {"using":"xpath","value":"//XCUIElementTypeSecureTextField[1]"}
>> proxy.js:67:16 [master] pid:6233 Got response with status 200: {"value":{"ELEMENT":"55DAE098-4923-4537-A636-D5A216C5E748","type":"XCUIElementTypeSecureTextField","label":null},"sessionId":"441a9989-60ff-4739-b4d2-50f27820434d","status":0}
>> session.js:107:14 [master] pid:6233 Send HTTP Respone to Client: {"value":"{\"ELEMENT\":\"55DAE098-4923-4537-A636-D5A216C5E748\",\"type\":\"XCUIElementTypeSecureTextField\",\"label\":null}","sessionId":"441a9989-60ff-4739-b4d2-50f27820434d","status":0}
>> responseHandler.js:11:12 [master] pid:6233 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/element/55DAE098-4923-4537-A636-D5A216C5E748/value, jsonBody: {"value":["123456"]}
>> proxy.js:54:14 [master] pid:6233 Proxy: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/element/55DAE098-4923-4537-A636-D5A216C5E748/value:POST to http://172.18.156.69:8100/session/E869379A-680D-4CD5-AE7D-45BD6A3CF533/element/55DAE098-4923-4537-A636-D5A216C5E748/value:POST with body: {"value":["123456"]}
>> proxy.js:67:16 [master] pid:6233 Got response with status 200: {"status":0,"id":"55DAE098-4923-4537-A636-D5A216C5E748","value":"","sessionId":"441a9989-60ff-4739-b4d2-50f27820434d"}
>> session.js:107:14 [master] pid:6233 Send HTTP Respone to Client: {"status":0,"id":"55DAE098-4923-4537-A636-D5A216C5E748","value":"","sessionId":"441a9989-60ff-4739-b4d2-50f27820434d"}
>> responseHandler.js:11:12 [master] pid:6233 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/element, jsonBody: {"using":"name","value":"登录"}
>> proxy.js:54:14 [master] pid:6233 Proxy: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/element:POST to http://172.18.156.69:8100/session/E869379A-680D-4CD5-AE7D-45BD6A3CF533/element:POST with body: {"using":"name","value":"登录"}
>> proxy.js:67:16 [master] pid:6233 Got response with status 200: {"value":{"ELEMENT":"53C8C92A-CC62-451C-B960-7C427FD93AEB","type":"XCUIElementTypeButton","label":"登录"},"sessionId":"441a9989-60ff-4739-b4d2-50f27820434d","status":0}
>> session.js:107:14 [master] pid:6233 Send HTTP Respone to Client: {"value":"{\"ELEMENT\":\"53C8C92A-CC62-451C-B960-7C427FD93AEB\",\"type\":\"XCUIElementTypeButton\",\"label\":\"登录\"}","sessionId":"441a9989-60ff-4739-b4d2-50f27820434d","status":0}
>> responseHandler.js:11:12 [master] pid:6233 Recieve HTTP Request from Client: method: POST url: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/element/53C8C92A-CC62-451C-B960-7C427FD93AEB/click, jsonBody: {}
>> proxy.js:54:14 [master] pid:6233 Proxy: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d/element/53C8C92A-CC62-451C-B960-7C427FD93AEB/click:POST to http://172.18.156.69:8100/session/E869379A-680D-4CD5-AE7D-45BD6A3CF533/element/53C8C92A-CC62-451C-B960-7C427FD93AEB/click:POST with body: {}
>> proxy.js:67:16 [master] pid:6233 Got response with status 200: {"status":0,"id":"53C8C92A-CC62-451C-B960-7C427FD93AEB","value":"","sessionId":"441a9989-60ff-4739-b4d2-50f27820434d"}
>> session.js:107:14 [master] pid:6233 Send HTTP Respone to Client: {"status":0,"id":"53C8C92A-CC62-451C-B960-7C427FD93AEB","value":"","sessionId":"441a9989-60ff-4739-b4d2-50f27820434d"}
>> responseHandler.js:11:12 [master] pid:6233 Recieve HTTP Request from Client: method: DELETE url: /wd/hub/session/441a9989-60ff-4739-b4d2-50f27820434d, jsonBody: {}
>> macaca-ios.js:258:10 [master] pid:6233 Stoping iOS driver...
>> macaca-ios.js:284:10 [master] pid:6233 iOS driver cleaned up.
>> session.js:80:12 [master] pid:6233 Delete session, sessionId: 441a9989-60ff-4739-b4d2-50f27820434d
>> responseHandler.js:43:14 [master] pid:6233 Send HTTP Respone to Client: {"sessionId":"441a9989-60ff-4739-b4d2-50f27820434d","status":0}
>> xctest-client.js:123:16 [master] pid:6233 
Exiting...

>> xctest-client.js:156:14 [master] pid:6233 ** BUILD INTERRUPTED **

>> xctest-client.js:164:14 [master] pid:6233 xctest client exit with code: null, signal: SIGTERM
>> xctest-client.js:131:16 [master] pid:6233 bootstrap exit with code: 0, signal: null
```

**Comment by xudafeng** [comment]
升级 macaca-ios 驱动，如真机遇到问题，请到社区看解决办法

**Comment by 183181731** [comment]
@xudafeng  是否有认真看过我的问题，真机运行已经OK了，可是在执行case的时候会有概率碰到这个问题 。。脚本无任何改动重新运行有时候又可以了，我看了和这个issue类是吧。https://github.com/alibaba/macaca/issues/204

**Comment by xudafeng** [comment]
@183181731 重新执行又好了？

**Comment by 183181731** [comment]
@xudafeng  是的  而且概率很大    经常出现，完全找不到规律，出错和正常的LOG都发上面了

**Comment by hujiachun** [comment]
@xudafeng  怎么关了？是什么问题?

**Comment by candialala** [comment]
@183181731 有解决方案了么，我也是一直碰到这个问题

**Comment by xudafeng** [comment]
升级macaca-cli macaca-ios

**Comment by candialala** [comment]
@xudafeng 升级后还是很大概率会出现

> > proxy.js:58:18 [master] pid:22744 xctest client proxy error with: Error: connect ETIMEDOUT 172.17.6.171:8100
> > /usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169
> >   throw new Error(res);
> >   ^

Error: >> proxy.js:58:18 [master] pid:22744 xctest client proxy error with: Error: connect ETIMEDOUT 172.17.6.171:8100
    at Logger.error (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request._callback (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by xudafeng** [comment]
@candialala  刚升级的？

wifi开了吗

**Comment by candialala** [comment]
@xudafeng 对，刚安装的，wifi开了

**Comment by candialala** [comment]
@xudafeng 首次装WebDriverAgentRunner后，第一次执行脚本是可以的。然后接下来就一直不行。

**Comment by 183181731** [comment]
@candialala 找到原因了，自己解决的，原因是xctest-client.js里设置的sleep时间太短了导致WDA还没启动macaca就已经开始去访问8100了，将xctest-clients.js中的yield _.sleep(10000); 的sleep时间增加就可以了，具体看你真机的启动速度，我改成了yield _.sleep(20000); 就是20秒，就可以了，不会碰到此问题了。
xctest-clients.js文件的位置在/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/lib/xctest-client.js

**Comment by xudafeng** [comment]
@183181731 可以分享一文章吗

**Comment by 183181731** [comment]
@xudafeng OK

**Comment by xudafeng** [comment]
https://testerhome.com/topics/6086

**Comment by candialala** [comment]
@183181731 但我还是有这样的问题

> > proxy.js:58:18 [master] pid:42138 xctest client proxy error with: Error: connect ETIMEDOUT 172.17.3.35:8100
> > /usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169
> >   throw new Error(res);
> >   ^

Error: >> proxy.js:58:18 [master] pid:42138 xctest client proxy error with: Error: connect ETIMEDOUT 172.17.3.35:8100
    at Logger.error (/usr/local/lib/node_modules/macaca-ios/node_modules/xlogger/lib/xlogger.js:169:9)
    at Request._callback (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/lib/proxy.js:58:18)
    at self.callback (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:199:22)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (/usr/local/lib/node_modules/macaca-ios/node_modules/xctest-client/node_modules/request/request.js:821:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at Socket.socketErrorListener (_http_client.js:269:9)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at emitErrorNT (net.js:1269:8)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)

**Comment by 183181731** [comment]
@candialala 你这个错误和我的不一样，你的是TIMEDOUT，这个应该是跟这个问题一样https://github.com/facebook/WebDriverAgent/issues/288
