### ISSUE TITLE
case `uname` in SyntaxError: Unexpected token case (windows) with mocha

### ISSUE THREAD

**Issue by callblueday** [macacajs/macaca-cli#66]
When I run macaca-mobile-sample-test.js in windows, there are some errors. 

```
D:\myprojects\macacaSample\mobile-app-sample-nodejs>macaca run -d macaca-test\mobile-app-sample.test
.js
>> webdriver sdk launched
>> D:\myprojects\macacaSample\mobile-app-sample-nodejs\node_modules\.bin\mocha:4
case `uname` in
^^^^

SyntaxError: Unexpected token case
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

>> Test completed!
```

My node version is `4.2.2`. How can i fix it?

**Comment by xudafeng** [comment]
https://testerhome.com/topics/node68
